/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vezerlok;

import java.util.Random;



/**
 *
 * @author Szilvi
 */
public class CsoportMunka extends javax.swing.JFrame {
    

    /**
     * Creates new form CsoportMunka
     */
    public CsoportMunka() {
        initComponents();
        randomGenerator();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnellenorzes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbfeladatok = new javax.swing.JLabel();
        lbJoRossz = new javax.swing.JLabel();
        txtfmegoldas = new javax.swing.JTextField();
        btnujra = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnosztas = new javax.swing.JMenu();
        mniosszead = new javax.swing.JMenuItem();
        mnikivon = new javax.swing.JMenuItem();
        mniszoroz = new javax.swing.JMenuItem();
        mniosztas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Megoldásod:");

        btnellenorzes.setText("Ellenőrzés");
        btnellenorzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnellenorzesActionPerformed(evt);
            }
        });

        lbfeladatok.setText("Feladat:");

        lbJoRossz.setText("Jó vagy Rossz");

        btnujra.setText("Újra");
        btnujra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnujraActionPerformed(evt);
            }
        });

        mnosztas.setText("Feladatok");

        mniosszead.setText("Összeadás");
        mniosszead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniosszeadActionPerformed(evt);
            }
        });
        mnosztas.add(mniosszead);

        mnikivon.setText("Kivonás");
        mnikivon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnikivonActionPerformed(evt);
            }
        });
        mnosztas.add(mnikivon);

        mniszoroz.setText("Szorzás");
        mniszoroz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniszorozActionPerformed(evt);
            }
        });
        mnosztas.add(mniszoroz);

        mniosztas.setText("Osztás");
        mniosztas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniosztasActionPerformed(evt);
            }
        });
        mnosztas.add(mniosztas);

        jMenuBar1.add(mnosztas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnellenorzes)
                                .addGap(77, 77, 77)
                                .addComponent(btnujra))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbfeladatok)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addComponent(txtfmegoldas, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(lbJoRossz, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(lbfeladatok)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfmegoldas, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbJoRossz)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnellenorzes)
                    .addComponent(btnujra))
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  Random rnd = new Random();
  int szam1=0;
  int szam2=0;
  double eredmeny=0;
  int muveletTipus=0;
  
     
    private void randomGenerator()
    {
    szam1=rnd.nextInt(10)+1;
    szam2=rnd.nextInt(10)+1;
    
    if(muveletTipus==0)
    {
    eredmeny=szam1*szam2;
     lbfeladatok.setText(szam1+" * "+szam2);  
    }
    else if(muveletTipus==1)
    {
    eredmeny=szam1-szam2;
    lbfeladatok.setText(szam1+" - "+szam2); 
    }
    else if(muveletTipus==2)
    {
    eredmeny=szam1+szam2;
    lbfeladatok.setText(szam1+" + "+szam2); 
    }
    else
    {
      eredmeny=szam1/szam2;
      lbfeladatok.setText(szam1+" / "+szam2); 
    }
    
    
    
    }
  
    private void mniosszeadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniosszeadActionPerformed
        szam1=rnd.nextInt(10)+1;
    szam2=rnd.nextInt(10)+1;
        muveletTipus=2;
       
         eredmeny=szam1+szam2;
    lbfeladatok.setText(szam1+" + "+szam2); 
    
         
    }//GEN-LAST:event_mniosszeadActionPerformed

    private void btnujraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnujraActionPerformed
         szam1=rnd.nextInt(10)+1;
    szam2=rnd.nextInt(10)+1;
    
    if(muveletTipus==0)
    {
    eredmeny=szam1*szam2;
     lbfeladatok.setText(szam1+" * "+szam2);  
    }
    else if(muveletTipus==1)
    {
    eredmeny=szam1-szam2;
    lbfeladatok.setText(szam1+" - "+szam2); 
    }
    else if(muveletTipus==2)
    {
    eredmeny=szam1+szam2;
    lbfeladatok.setText(szam1+" + "+szam2); 
    }
    else
    {
      eredmeny=szam1/szam2;
      lbfeladatok.setText(szam1+" / "+szam2); 
    }      
                
    
    }//GEN-LAST:event_btnujraActionPerformed
    private void btnellenorzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnellenorzesActionPerformed
      int megoldas=   Integer.parseInt(txtfmegoldas.getText());
      if(megoldas==eredmeny)
      {
      lbJoRossz.setText("Jó megoldás");
      }
      else 
      {
      lbJoRossz.setText("Rossz megoldás");
      }
    }//GEN-LAST:event_btnellenorzesActionPerformed

    private void mniosztasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniosztasActionPerformed
      szam1=rnd.nextInt(10)+1;
    szam2=rnd.nextInt(10)+1;
          muveletTipus=3;
           
           eredmeny=szam1/szam2;
      lbfeladatok.setText(szam1+" / "+szam2);
    }//GEN-LAST:event_mniosztasActionPerformed

    private void mnikivonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnikivonActionPerformed
        szam1=rnd.nextInt(10)+1;
    szam2=rnd.nextInt(10)+1;
        muveletTipus=1;
         
         eredmeny=szam1-szam2;
    lbfeladatok.setText(szam1+" - "+szam2);
    }//GEN-LAST:event_mnikivonActionPerformed

    private void mniszorozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniszorozActionPerformed
        szam1=rnd.nextInt(10)+1;
    szam2=rnd.nextInt(10)+1;
        muveletTipus=0;
         
         eredmeny=szam1*szam2;
     lbfeladatok.setText(szam1+" * "+szam2);
    }//GEN-LAST:event_mniszorozActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CsoportMunka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CsoportMunka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CsoportMunka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CsoportMunka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CsoportMunka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnellenorzes;
    private javax.swing.JButton btnujra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbJoRossz;
    private javax.swing.JLabel lbfeladatok;
    private javax.swing.JMenuItem mnikivon;
    private javax.swing.JMenuItem mniosszead;
    private javax.swing.JMenuItem mniosztas;
    private javax.swing.JMenuItem mniszoroz;
    private javax.swing.JMenu mnosztas;
    private javax.swing.JTextField txtfmegoldas;
    // End of variables declaration//GEN-END:variables


}
